version: '3.8'

services:
  # PostgreSQL Database
  postgres:
    image: postgres:15-alpine
    container_name: smart_redirect_postgres_dev
    environment:
      POSTGRES_DB: smart_redirect
      POSTGRES_USER: smartredirect
      POSTGRES_PASSWORD: smart123
    ports:
      - "5432:5432"
    volumes:
      - postgres_data_dev:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U smartredirect"]
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - smart_redirect_dev

  # Redis Cache
  redis:
    image: redis:7-alpine
    container_name: smart_redirect_redis_dev
    ports:
      - "6379:6379"
    volumes:
      - redis_data_dev:/data
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 10s
      timeout: 3s
      retries: 5
    networks:
      - smart_redirect_dev

  # Adminer for Database Management
  adminer:
    image: adminer
    container_name: smart_redirect_adminer
    ports:
      - "8081:8080"
    environment:
      ADMINER_DEFAULT_SERVER: postgres
    depends_on:
      - postgres
    networks:
      - smart_redirect_dev

volumes:
  postgres_data_dev:
  redis_data_dev:

networks:
  smart_redirect_dev:
    driver: bridge