groups:
  - name: smart_redirect_alerts
    rules:
      # High response time
      - alert: HighResponseTime
        expr: histogram_quantile(0.95, rate(http_request_duration_seconds_bucket[5m])) > 0.5
        for: 2m
        labels:
          severity: warning
        annotations:
          summary: "High response time detected"
          description: "95th percentile response time is above 500ms for 2 minutes"

      # High error rate
      - alert: HighErrorRate
        expr: rate(http_requests_total{status=~"5.."}[5m]) > 0.1
        for: 1m
        labels:
          severity: critical
        annotations:
          summary: "High error rate detected"
          description: "Error rate is above 10% for 1 minute"

      # Database connection issues
      - alert: DatabaseConnectionDown
        expr: up{job="postgres_exporter"} == 0
        for: 1m
        labels:
          severity: critical
        annotations:
          summary: "Database connection down"
          description: "PostgreSQL database is not accessible"

      # Redis connection issues
      - alert: RedisConnectionDown
        expr: up{job="redis_exporter"} == 0
        for: 1m
        labels:
          severity: critical
        annotations:
          summary: "Redis connection down"
          description: "Redis cache is not accessible"

      # High memory usage
      - alert: HighMemoryUsage
        expr: (1 - (node_memory_MemAvailable_bytes / node_memory_MemTotal_bytes)) * 100 > 85
        for: 5m
        labels:
          severity: warning
        annotations:
          summary: "High memory usage"
          description: "Memory usage is above 85% for 5 minutes"

      # High CPU usage
      - alert: HighCPUUsage
        expr: 100 - (avg by (instance) (rate(node_cpu_seconds_total{mode="idle"}[5m])) * 100) > 80
        for: 10m
        labels:
          severity: warning
        annotations:
          summary: "High CPU usage"
          description: "CPU usage is above 80% for 10 minutes"

      # Disk space usage
      - alert: DiskSpaceUsage
        expr: (1 - (node_filesystem_avail_bytes / node_filesystem_size_bytes)) * 100 > 85
        for: 5m
        labels:
          severity: warning
        annotations:
          summary: "High disk usage"
          description: "Disk usage is above 85% for 5 minutes"

      # Application down
      - alert: ApplicationDown
        expr: up{job="smart_redirect"} == 0
        for: 1m
        labels:
          severity: critical
        annotations:
          summary: "Smart Redirect application down"
          description: "Smart Redirect application is not responding"