server:
  port: 8080
  mode: release

database:
  postgres:
    host: postgres
    port: 5432
    user: postgres
    password: postgres
    dbname: smart_redirect
    sslmode: disable
    max_idle_conns: 10
    max_open_conns: 100
    conn_max_lifetime: 3600

redis:
  addr: redis:6379
  password: ""
  db: 0
  pool_size: 10

security:
  jwt_secret: ${JWT_SECRET:-your-production-secret-key-here}
  jwt_expire_hours: 24

rate_limit:
  ip_limit_per_hour: 1000
  ip_link_limit_per_12h: 50
  global_daily_cap: 10000000
  api_limit_per_hour: 200
  redirect_limit_per_hour: 5000
  auto_block_threshold: 2000
  auto_block_duration_hours: 24

logging:
  level: info
  format: json
  output: stdout