global:
  scrape_interval: 15s
  evaluation_interval: 15s

rule_files:
  - "rules/*.yml"

alerting:
  alertmanagers:
    - static_configs:
        - targets:
          - alertmanager:9093

scrape_configs:
  # Prometheus itself
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']

  # Smart Redirect Application
  - job_name: 'smart_redirect'
    static_configs:
      - targets: ['smart_redirect:8080']
    metrics_path: /metrics
    scrape_interval: 10s

  # Node Exporter
  - job_name: 'node_exporter'
    static_configs:
      - targets: ['node_exporter:9100']

  # Redis Exporter
  - job_name: 'redis_exporter'
    static_configs:
      - targets: ['redis_exporter:9121']

  # PostgreSQL Exporter
  - job_name: 'postgres_exporter'
    static_configs:
      - targets: ['postgres_exporter:9187']

  # Nginx metrics (if enabled)
  - job_name: 'nginx'
    static_configs:
      - targets: ['nginx:9113']
    metrics_path: /metrics